# Install dependencies
FROM cirrusci/flutter:2.0.1

# Install web sdk
RUN flutter precache --web 

# Make folder for project
WORKDIR /app

# Copy context of docker build into /app
COPY . .

# Get app packages
RUN flutter pub get

# Build app for web using skia => webassembly using webgl
RUN flutter build web --web-renderer canvaskit --release

# Final docker stage.
FROM nginx

# Copy build output from first stage into dir that nginx serves
COPY --from=0 /app/build/web /usr/share/nginx/html

# Copy local build from root dir into dir that nginx serves 
#COPY ./build/web/ /usr/share/nginx/html

# Copy nginx config from root dir into nginx config
COPY nginx.config /etc/nginx/nginx.conf

# Document the exposed port
EXPOSE  8080

# Serve that build
CMD [ "nginx", "-g", "daemon off;" ]